### PR TITLE
Upgrade-voice-conversion-backend

### PR DESCRIPTION
**Pull request by JackismyShephard**
# CHANGELOG

This PR upgrades the RVC based voice conversion backend with up to date changes inspired by the work done by the Applio team.

An RVC package (`ultimate_rvc.rvc`) based on the work of Appplio was already added in a previous PR. This PR makes slight changes to that package (primarily, its inference sub-package, i.e. `ultimate_rvc.rvc.infer`) so that it works with the Ultimate RVC project. Additionally, both the backend (`ultimate_rvc.core`), cli (`ultimate_rvc.cli`) and frontend `ultimate_rvc.web` packages are updated so that they properly expose the new voice conversion functionality from the RVC package. A detailed overview of the changes implemented by this PR is provided below.

#### Type annotations

* Let the location of models, audio, temp and voice models directories be defined by corresponding environment variables if they exist. These are:
  * `URVC_MODELS_DIR`
  * `URVC_AUDIO_DIR`
  * `URVC_TEMP_DIR`
  * `URVC_VOICE_MODELS_DIR`

* annotate all (non empty) modules with `from __future__ import annotations` to enable deferred evaluation of type annotations.
  * This allows us to put definitions which are only used for type checking inside af a `if TYPE_CHECKING:` block
  * which by extensions means such definitions will not be imported at runtime and hence reducing overall startup time.
  * NOTE: this is primarily used to avoid importing gradio at runtime for the CLI app, which uses the core library that itself uses gradio for some typing.

* add enumerations for valid embedder models
* update enumeration for f0 methods by adding `FCPE`, `CREPE`, `CREPE-tiny` and removing `MANGIO_CREPE`

### RVC package

* move all rvc related models into the RVC models directory.
  * before they were hardcoded to be downloaded to the rvc package directory.
* correct the paths of config files so that they are relative to the root of the rvc package directory rather than the current working directory.
* fix numpy bug due to use of `np.int` which is no longer supported in latest version of Numpy.
* do not catch and print errors in `convert_audio` function from `infer.infer` module, as we want to fail fast and let the user know what went wrong.
* add package initialization script (`__init__.py`)
  * this script automatically calls `prequisites_download_pipeline` to download required embedders and predictors and sets up ffmpeg (which is required by the rvc package) using the `static_ffmpeg` python package.
  * Note that `prequisites_download_pipeline` is specifically not called with options to download pretrained models and executables (which is the default) as the former do not seem to be necessary for inference and the latter are not needed with the static ffmpeg binary already available.
* allow arbitrary combination of F0 methods to be provided rather than fixed strings denoting specific F0 method combinations
* lazily import `noisereduce` only when it is needed to save on startup time.
* convert printing from `infer.infer` and `infer.pipeline` modules into info level log statements.
  * and remove some specific "set log level" statements as we want the default log level to be propagated to the logger.
* add typing to functions used by `ultimate_rvc.core` so that pyright is appeased.

#### General

* Add pydantic model for directory meta data.
* consolidate the fields of the "ConvertedVocalsMeta" model with the updated parameters of the `convert` pipeline function from the `generate` module.
  * this includes a new field pointing to an instance of the above mentioned directory meta data model storing information on a given custom embedder model.
* Add new entity type for custom embedder models, which is used to report errors when a custom embedder model is not found.

* move voice models from the root of the rvc models directory to a dedicated voice models sub-directory.
* Use the `.initialized` flag to additionally determine whether the helper function to download audio separator models should be called.
  * This is done solely due to that function requiring large imports which we want to avoid, if possible, at startup time.
* move the `.initialized` flag file from the rvc models directory to the root of the models directory.
  * That is more appropriate now that it is also used to control whether the audio separator models are downloaded.

* remove `download_base_models` as it is no longer needed now that we are downloading all required RVC models via `prequisites_download_pipeline`

#### Generate

* Fix buggy code for retrieving model and index file so that pipeline works with arbitrary mode file paths
* No longer call model setup script when initializing the package, as that is now done by the RVC package initialization script.
* optimize startup time by lazily importing `audio_separator.separator` from within the `_get_audio_separator` function and caching the retrieved `AudioSeparator` instance.
* Similarly define a wrapper function for retrieving an instance of the `VoiceConverter` from `ultimate_rvc.rvc.infer.infer` so that even more startup time is saved.

* update the signature of `_validate_exists` and `_validate_all_exist` so that the entity to be validated can have None type.
  * that is more appropriate as these functions are checking whether an entity is `None`.

* Update the `convert` pipeline function to be consistent with the new voice conversion functionality exposed by the `convert_audio` function from `rvc.infer.infer` module. Specifically:

  * update parameters based on those exposed by the `convert_audio` function from `rvc.infer.infer`.
    * f0 methods are given as a list which is then converted to a set to remove duplicates if not None (If None then a default set containing just the RVMPE method is passed on)
    * We do not provide values for some parameters of the `convert_audio` function, namely
      * Those related to formant shifting, audio upscaling and F0 curve files as those parameter either dont work or don't make sense
      * Those related to voice postprocessing as that is something we prefer to do in a separate pipeline step.
    * rename `protect` parameter to `protect_rate`.

  * Add input validation for custom embedder model paths.

  * Add waveification pre-processing for aac and m4a formats as the `convert_audio` function from `rvc.infer.infer` cannot handle those audio formats.

  * Remove the old `_convert` function as it is no longer needed. Instead `_get_rvc_files` is called from `convert` directly to retrieve the model and index files to pass on to the `convert_audio` function.

* Update the `run_pipeline` function accordingly, so that it exposes the same parameters as the new `convert` function and calls that function correctly with the provided parameters.

#### Manage models and audio

* optimize the `delete_all_audio` a bit by removing the audio directory in one go rather than its two subdirectories separately.
* optimize `delete_all_models` similarly by removing the models directory in one go rather than each voice model directory separately.
* simplify `get_saved_model_names` a bit now that there are no loose files to exclude from the list of retrieved model directories.

### CLI

* add and use enumeration for audio generation panel names to avoid accidentally generating invalid panels
* add autocompletion function for embedder models
* print total execution time after completion of each CLI command
* add new `convert` command to the generate song cover part of the ultimate RVC CLI
  * This command exposes the `convert` function from the backend (`core.generate.song.cover`) to the CLI
* update the `run_pipeline` function so that its voice conversion parameters are consistent with the new parameters exposed by the `convert` function from the backend (`core.generate.song.cover`)
* update the voice conversion parameter help messages so that they are more informative (and more in line with the help text that the `rvc-cli`package provides)

#### General

* Increase the render time for pop-up notification messages from 0.5 sec to 1.0 sec
* add a `toggle_visibility` function which toggles the visibility of a given component based on the equality of a value and a target.
* attempt to fix `ConnectionResetError` exceptions by re-introducing a previous (now deleted) fix which changes event loop policy on Windows to `asyncio.WindowsSelectorEventLoopPolicy()`
* do manual alignment of component input/output boxes by using `<br>` tags to extend info text vertically (not ideal)

#### Multi step generation

* Add components corresponding to new parameters exposed by the `convert` function from the backend (`ultimate_rvc.core.generate.song.cover`)
  * Specifically a row with checkboxes corresponding to `split_vocals`, `autotune_vocals` and `clean_vocals` where the latter two when clicked will result in slider components corresponding to `autotune_strength` and `clean_strenght` being shown below.
  * Another row with a dropdown component corresponding to the `embedder_model` parameter and a number component corrsponding to the `sid` parameter, where the former when clicked will result in a textbox corresponding to the `custom_embedder_model` parameter being shown below.
* additionally the dropdown component for f0 methods is changed to be multi-selectable now that we are allowing arbitrary combinations of f0 methods to be provided.
* Given the many voice conversion parameters now available, these are grouped into sub accordions under the "step 2" accordion, which are by default closed to not clutter the interface too much. The names of these accordions correspond to the new panel names used for the CLI.
* The order of the components in the UI is updated to reflect the order of the corresponding parameters in the `convert` function from the backend (`ultimate_rvc.core.generate.song.cover`).
  This just means moving the F0 methods component to be the first "optional" component under the "step 2" accordion.
* The help text for the component is consolidated with the help text for the corresponding parameters from the CLI.
  * Sometimes the help text here is shortened for the visual space available.

#### Single step generation

* Add components corresponding to new parameters exposed by the `convert` function from the backend (`ultimate_rvc.core.generate.song.cover`) like it is done for the multi step generation tab
  * the only difference here being that the components are not grouped into accordions but rather separated with markdown headers.

## Project Managemet

* Update dependencies
  * Promote `typer` to 0.14.0
  * Promote `gradio` to 5.7.1
  * Add `noisereduce`
    * as it is needed for noise reduction in the voice conversion pipeline
  * Add `local-attention` and `transformers`
    * as they are needed for initializating contentvec for the voice conversion pipeline
  * Add `einops`
  * Add `wget`
    * as it is needed for downloading the pretrained models
  * Remove `fairseq-fixed`as it is not longer needed
  * Tentatively remove (comment out) `praat-parselmouth`
    * as it is not needed until we will be using functionality such as its "Change Gender" command for formant shifting
  * Tentatively remove (comment out) `pyworld`
    * as it is not needed until we will be using its method for dio, pm and harvest based pitch extraction
* update powershell setup script
  * use camel case for variable names
  * add JS node path to `GRADIO_NODE_PATH` environment variable so that SSR mode will work on windows.
* update bash script
  * always install cuda 12.5 regardless of distro version, as it is backwards compatible with cuda 12.4
  * fix problems with compiling diffq on ubuntu 24.04 by installing `build-essential` apt package.

### CODE REVIEW

**Comment by SpyC0der77** [comment]
what does dis do? is this make it use gradio 5 or what? Make it use cpu instead of gpu?

**Comment by JackismyShephard** [comment]
@SpyC0der77 Ultimate RVC is already using gradio 5. If you pull latest changes from master you should, amongst other things, notice some changes in the UI. This PR is updating the voice conversion functionality based on the work by the team at applio. I still have not gotten very far in the process but I think this might potentially improve the quality of generated song covers greatly.

Also, if you are interested in contributing to Ultimate RVC just let me know. I might have some tasks for you 😄

**Comment by SpyC0der77** [comment]
ye i want to contribute. I don't know much about this but I do know python

**Comment by JackismyShephard** [comment]
@SpyC0der77 that sounds great. If you are really serious about contributing we should probably coordinate a bit. Perhaps on discord or something. You can find me under the same username as here.

**Comment by SpyC0der77** [comment]
I don't have discord 💀 but I mean GitHub is fine for communicating ig (that is what I have previously done)

**Comment by JackismyShephard** [comment]
Yeah that is fine if you have something specific in mind that you want to make a pr for. But if you are interested in learning the code base I thinks it's easier discussing this in depth somewhere else.

**Comment by SpyC0der77** [comment]
check out my pr

**Review by JackismyShephard — COMMENTED** [review]
First draft of implementation seems to work. Still need to test all voice conversion options thorougly and clean up code.

**Pull request merged**
